// Generated by IcedCoffeeScript 108.0.9
(function() {
  var exit, page, system;

  page = require('webpage').create();

  system = require('system');

  exit = function(code) {
    phantom.onError = function() {
      return null;
    };
    setTimeout((function() {
      return phantom.exit(code);
    }), 5000);
    if (page) {
      return page.close();
    }
  };

  setTimeout((function() {
    return exit(1);
  }), 100000);

  page.open('http://hideme.ru/proxy-list/?maxtime=1500&ports=' + system.args[1] + '&type=h&anon=34', function(_) {
    var arr;
    arr = page.evaluate(function() {
      return [].slice.call(document.getElementsByClassName('tdl')).map(function(el) {
        return el.textContent;
      });
    });
    console.log(arr[Math.floor(Math.random() * arr.length)]);
    return exit(0);
  });

}).call(this);
